export const dailyMotivations: string[] = [
  "You don’t have to be extreme, just consistent.",
  "Small steps every day lead to big results.",
  "Believe you can, and you're halfway there.",
  "Discipline beats motivation.",
  "Your only limit is your mind.",
  "Dream big, start small, act now.",
  "Consistency is the key to success.",
  "Don’t stop until you’re proud.",
  "Be stronger than your excuses.",
  "Work hard in silence, let success make the noise.",
  "Push yourself, no one else will do it for you.",
  "Focus on progress, not perfection.",
  "Do it now. Sometimes ‘later’ becomes ‘never’.",
  "Turn your ‘I can’t’ into ‘I can’.",
  "Don’t wait for inspiration, create it.",
  "Great things take time.",
  "You are capable of more than you know.",
  "Doubt kills more dreams than failure ever will.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Don’t wish for it, work for it.",
  "Stay hungry, stay foolish.",
  "Nothing changes if nothing changes.",
  "Be a voice, not an echo.",
  "You are stronger than your challenges.",
  "Make it happen. Shock everyone.",
  "One day or day one, you decide.",
  "Don’t limit your challenges; challenge your limits.",
  "Focus on your goals, not your fear.",
  "Don’t let yesterday take up too much of today.",
  "Action is the foundational key to success.",
  "Start where you are. Use what you have. Do what you can.",
  "Fall seven times and stand up eight.",
  "Difficult roads often lead to beautiful destinations.",
  "Winners are not people who never fail, but those who never quit.",
  "Don’t wait for opportunity. Create it.",
  "Keep going. Everything you need will come to you at the right time.",
  "Don’t let small minds convince you your dreams are too big.",
  "Prove yourself to yourself, not others.",
  "It always seems impossible until it’s done.",
  "Do something today that your future self will thank you for.",
  "You can do hard things.",
  "The key to success is to start before you are ready.",
  "Don’t be afraid to start over. It’s a new chance to rebuild.",
  "Dare to begin.",
  "Be the energy you want to attract.",
  "The comeback is always stronger than the setback.",
  "What you get by achieving your goals is not as important as what you become.",
  "Do what you can with all you have.",
  "Stay focused and never give up.",
  "Your time is now.",
  "If it doesn’t challenge you, it won’t change you.",
  "Act as if what you do makes a difference. It does.",
  "Keep pushing. You are getting there.",
  "Success doesn’t come to you, you go to it.",
  "Start today. Not tomorrow.",
  "Don’t be afraid to be different.",
  "Make today amazing.",
  "The best way to get started is to quit talking and begin doing.",
  "Courage is one step ahead of fear.",
  "Never stop learning.",
  "Do it with passion or not at all.",
  "Focus on being productive, not busy.",
  "Go the extra mile. It’s never crowded.",
  "Your attitude determines your direction.",
  "Hustle until you no longer have to introduce yourself.",
  "Good things happen to those who hustle.",
  "You are braver than you believe.",
  "Do something today that scares you.",
  "Turn obstacles into opportunities.",
  "Be relentless in the pursuit of your dreams.",
  "You have survived 100% of your bad days.",
  "Focus on what you can control.",
  "Don’t look back, you’re not going that way.",
  "Never give up on a dream just because of the time it will take.",
  "Success is the sum of small efforts repeated daily.",
  "Stay positive, work hard, make it happen.",
  "Do more of what makes you happy.",
  "Fall in love with the process.",
  "Your hard work will pay off.",
  "Every day is a chance to improve yourself.",
  "You didn’t come this far only to come this far.",
  "Good things take time, but they’re worth it.",
  "One positive thought can change your whole day.",
  "You’re capable of amazing things.",
  "Do your best and forget the rest.",
  "Focus. Commit. Succeed.",
  "Start now, get perfect later.",
  "Your goals don’t care how you feel.",
  "Don’t fear failure. Fear regret.",
  "Consistency is what transforms average into excellence.",
  "Great things never come from comfort zones.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Be fearless in pursuit of what sets your soul on fire.",
  "You’ve got this.",
  "Be proud of how far you’ve come.",
  "Success starts with self-discipline.",
  "Your future is created by what you do today.",
  "Keep your head high and your spirits higher.",
  "If you can dream it, you can do it.",
  "Stop doubting yourself and work hard.",
  "Rise and grind.",
  "Be unstoppable."
];
