export const joyTasks: string[] = [
  "Feel the morning sun on your face.",
  "Take a short walk in nature.",
  "Listen to your favorite song.",
  "Drink a hot cup of tea or coffee.",
  "Call a loved one just to say hello.",
  "Watch a funny video.",
  "Write down three things you’re grateful for.",
  "Stretch for 5 minutes.",
  "Hug someone you love.",
  "Sit quietly and take 10 deep breaths.",
  "Cook your favorite meal.",
  "Read a book for 10 minutes.",
  "Watch the sunrise or sunset.",
  "Light a scented candle.",
  "Look at old happy photos.",
  "Treat yourself to a snack you love.",
  "Compliment a stranger.",
  "Spend time with your pet.",
  "Dance to a fun song.",
  "Draw or doodle something silly.",
  "Send a thank-you message to someone.",
  "Make your bed.",
  "Clean a small corner of your home.",
  "Play a game you enjoy.",
  "Visit a park or garden.",
  "Smile at someone.",
  "Sing in the shower.",
  "Plan something fun for the weekend.",
  "Put on your coziest clothes.",
  "Do a random act of kindness.",
  "Water your plants.",
  "Look at the stars at night.",
  "Write yourself a love note.",
  "Play with a child.",
  "Paint or color.",
  "Take a warm bath.",
  "Walk barefoot on grass.",
  "Close your eyes and listen to nature sounds.",
  "Learn something new for fun.",
  "Eat a piece of chocolate slowly.",
  "Look at clouds and find shapes.",
  "Spend 5 minutes doing nothing.",
  "Call an old friend.",
  "Make a playlist of your favorite songs.",
  "Watch a comfort movie.",
  "Bake cookies or a cake.",
  "Declutter a drawer.",
  "Wear your favorite outfit.",
  "Do a puzzle or crossword.",
  "Try a new hobby.",
  "Write a short poem.",
  "Make a vision board.",
  "Try a new recipe.",
  "Visit a new café.",
  "Pet a dog or cat.",
  "Watch the rain from your window.",
  "Go for a drive with music on.",
  "Buy yourself flowers.",
  "Take a photo walk.",
  "Watch a comedy show.",
  "Write in your journal.",
  "Lie down and look at the ceiling.",
  "Send a voice note to a friend.",
  "Go to bed early.",
  "Try a new hairstyle.",
  "Make origami.",
  "Eat breakfast outdoors.",
  "Look at your old school photos.",
  "Draw something with your non-dominant hand.",
  "Make a hot chocolate.",
  "Play an instrument.",
  "Go for a slow bike ride.",
  "Give yourself a mini facial.",
  "Try a yoga pose.",
  "Make a bucket list.",
  "Take a nap in the afternoon.",
  "Do something spontaneous.",
  "Sit under a tree.",
  "Put on red lipstick (or bold color).",
  "Send a meme to a friend.",
  "Wear mismatched socks.",
  "Write a short story.",
  "Re-watch your favorite childhood cartoon.",
  "Make a friendship bracelet.",
  "Decorate your workspace.",
  "Drink water from your fanciest glass.",
  "Sit by the window and people-watch.",
  "Wrap yourself in a blanket burrito.",
  "Plan your dream vacation.",
  "Try a new dessert.",
  "Pick a random podcast to listen to.",
  "Take silly selfies.",
  "Look up inspirational quotes.",
  "Sit by a fireplace.",
  "Do a small craft project.",
  "Compliment yourself in the mirror.",
  "Listen to calming nature sounds.",
  "Try meditation for 5 minutes."
];
